# Generated by Django 5.2.6 on 2025-09-19 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bpm', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low')], default='normal', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HeartRate',
                'verbose_name_plural': 'HeartRates',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('is_discharge', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PatientAdmission',
                'verbose_name_plural': 'PatientAdmissions',
            },
        ),
    ]
