# Generated by Django 5.2.6 on 2025-09-19 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='heartrate',
            name='handled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heartrate',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='admitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='assigned_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.device'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='heartrate',
            name='admission_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientadmission'),
        ),
    ]
