# Generated by Django 5.2.6 on 2025-09-19 08:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeartRate',
            new_name='PatientHeartRate',
        ),
    ]
