# Generated by Django 5.2.6 on 2025-09-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_heartrate_patientheartrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['first_name'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='patientadmission',
            options={'ordering': ['-admission_date'], 'verbose_name': 'PatientAdmission', 'verbose_name_plural': 'PatientAdmissions'},
        ),
        migrations.AlterModelOptions(
            name='patientheartrate',
            options={'ordering': ['-measured_at'], 'verbose_name': 'HeartRate', 'verbose_name_plural': 'HeartRates'},
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
